# -*- coding: utf-8 -*-
"""Ciclovias_RJ.RJ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yoTMTNNcb7sPiBhUG9rx3e_1_WrO2dsI
"""

!pip install geopandas
!pip install matplotlib
!pip install descartes

!pip install ipython

!pip install jupyter

import geopandas as gpd

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

dados_ciclovia = gpd.read_file('/content/sample_data/Marica_Ciclovias11Dez2020.geojson')

dados_ciclovia['geometry']

mapa_rj = gpd.read_file('/content/sample_data/33MUE250GC_SIR.shp')

marica_rj = mapa_rj.loc[(mapa_rj['NM_MUNICIP'] == 'MARICÁ')]

marica_rj.plot(color='RED', edgecolor='green', figsize=(12, 12))

# mapear as vias e integrar

# municip_rj = mapa_rj.loc[(mapa_rj['NM_MUNICIP'] == 'RIO DE JANEIRO')]
# municip_rj.plot(color='white',edgecolor='black', figsize=(12,12))

base = marica_rj.plot(color='red', edgecolor='black', figsize=(15, 18))
dados_ciclovia.plot(ax=base,figsize=(12,12))

# Codigo original para as ciclovias da cidade do RIO/RJ ThiagoDV/Bastter